hash-format = "sha256"
hash = "B0FE7BC618502D868A5B98A3562552FA6BB769E1750B354135076E3F073D4D0A"

[[files]]
file = "https://forms.gamer-sanctuary904.net/mods/worldedit-mod-7.2.12.jar"
hash = "1426645459FA4A0BEDFEDDF2AA0E69416D9676DC022AAF879333AEA89D7794DD"

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/config/custom-hud/profile1.txt"
hash = "10d7691ad85825af13bb637bb96ea7235e4e4886dbc48b490d6d34c7b9476265"

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/config/resourcepackupdater.json"
hash = "24552d1febc131d3b3264da989b1b8b3d2b60cda2023440fe9d084517e8ad06f"

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/MTR-LU-Addon-fabric-1.19.2-2.1.1.jar"
hash = "7be661f5a397e7b0433ef3623acde3a437a88ed24309813ff68d8b8e3bbcaa85"

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/carpet.pw.toml"
hash = "c4370993f7932be5e9eb2189a67f69330e724322ea6f39aac963d310af97444e"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/chat-heads.pw.toml"
hash = "c419054516c521d0942ad8bbc716c4b819022634eafc25c4c97857ea919944b1"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/continuity.pw.toml"
hash = "9527ab0fb84b5f9752976dff117fe326e3c1e59d777e3265d13262a739f66ece"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/controlling.pw.toml"
hash = "2e30808f998481e8e17b995fcd74394e0a7aaace16be55a0292f3f80157df578"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/customhud.pw.toml"
hash = "e9df207723ef5b171150d1c7a30d8da54a43e6a0dc1461f564396d36fc632c14"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/distanthorizons.pw.toml"
hash = "602610825e73d9b0fb1684911ef9cb8c8673b7d85d8636d5d50719f7d9ff9ff8"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/fabric-api.pw.toml"
hash = "5197e9172dd9a9b06303b85a837e7a044b71c005b3d0003aa19041a253daf541"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/fabric-language-kotlin.pw.toml"
hash = "1f5d80bccee13ecf7042644d74b32ddb45e47a2bc28b6da8aabe58620ac7fe87"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/freecam.pw.toml"
hash = "01d387e74048a56e3270f9018d57196bfb9f4476d386e7c2a22ac73f35f48de8"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/immediatelyfast.pw.toml"
hash = "865ffbf85ebd23860b712a6c0bd1857d0816c36415443a5e32d9aa385ff625d4"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/indium.pw.toml"
hash = "e8168531c092676d47cac3657bfc525f096f11ff5372ce6e322ad57778b81635"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/iris.pw.toml"
hash = "14e50c7cd16b4650d3a491f5f31bc00af6be0c290734db9552852ab1de9bc3bb"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/jcm.pw.toml"
hash = "e2ce890a206d6ad6807c2bc85559159eef55426566e982c4e05c14d3ae7033f7"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/language-reload.pw.toml"
hash = "5731d6f6b7e80dc61d88b85e366750b3c5f4a063c54af83d5e782792052decfc"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/lithium.pw.toml"
hash = "54a337d13450b35dfc931e7a5f3ed9fca1a1992ec51d3b1e4ea1cb5f7cd2d09c"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/minecraft-transit-railway.pw.toml"
hash = "a8c9353a4a5b4d08823f39e13dd10f04e1c884e5fa5aedae511a26d111a76d8a"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/modmenu.pw.toml"
hash = "be0fd8b9cd9f8a94428ea8ac5ec84f4f7bab23697236b7a2e54d8537834e0315"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/mtr-nte.pw.toml"
hash = "22e4bb0bde531b78f5ae642dd2b87c147ea116da03bf6a768b7ce724711cc0a2"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/no-chat-reports.pw.toml"
hash = "1aa7510ec1a3994273a20f8b341f676583b9ede2eaea3badd46deb7178d92a6c"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/reeses-sodium-options.pw.toml"
hash = "17651adb28b085101dcded29ef037e6622849a98b21d1c1872185e7b241a32f6"
metafile = true

[[files]]
file = "mods/resourcepackupdater-1.19.2-2.3.0.jar"
hash = "3709917217c4712b4a654ec89d914ccc9c24e22e9068bc3c37a5dafadb873638"

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/russian-metro-addon.pw.toml"
hash = "6eb04e29e0e7054979b9c48405bed438f953a5e17e64cfd0bf8753ef8c962f65"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/slideshow-fabric.pw.toml"
hash = "8fbc9c1c6bfe9eaed2e16603895d2a4cea4fede794fe8701b448addba73a326a"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/sodium-extra.pw.toml"
hash = "8da0d4c285e7e57aee3f08ab4e268d04518704ace4060744f042aef3a7f6bc50"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/sodium.pw.toml"
hash = "aa4dcf55ac3191b0b31437521714c1d28364c3396cf06ef07fa76a08488c1837"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/starlight.pw.toml"
hash = "2aeab4f3b0a720ed02f400d9b521f1858474d4f8f7c3577ce916d5aa31fe37e1"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/station-decoration.pw.toml"
hash = "19c234dccae3896624b605a204e738f4117913f963210c1da27d696fe457e2d1"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/worldeditcui-fabric.pw.toml"
hash = "61f75318d7335953e82b4504a91bd002822e863ee309e5a848ed6865409716de"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/xaeros-minimap.pw.toml"
hash = "8d9f7a879d69a18836da27afea0700f5e34aa39366d3bc80b60ca3942b92f9d0"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/xaeros-world-map.pw.toml"
hash = "d5b1f3f1683ddc0b5597a7f277de8dc6099fdad1d6ec2610a4d78f5a857615a9"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/yacl.pw.toml"
hash = "80bab11e8d1438ec93695050f087dc2f9d0ae1d2523a17b8236af7029f14119e"
metafile = true

[[files]]
file = "https://minecraft-transit-railway.github.io/LetsPlay-Packwiz/mods/zoomify.pw.toml"
hash = "14bbcbe63a7b5e7c03d707cb0145c231f07e1fae4bd8c5233db2a610998428e5"
metafile = true
